In [5]:
import pandas as pd

products = {
    "Product Name": ["Laptop", "Phone", "Tablet", "Headphones", "Smartwatch"],
    "Price": [60000, 45000, 25000, 2000, 8000],
    "Category": ["Electronics", "Electronics", "Electronics", "Accessories", "Electronics"]
}

df = pd.DataFrame(products)
df["Discounted Price"] = df["Price"] * 0.9
print("Products DataFrame:\n", df)

print("\nProducts cheaper than 500:\n", df[df["Price"] < 500])


Products DataFrame:
   Product Name  Price     Category  Discounted Price
0       Laptop  60000  Electronics           54000.0
1        Phone  45000  Electronics           40500.0
2       Tablet  25000  Electronics           22500.0
3   Headphones   2000  Accessories            1800.0
4   Smartwatch   8000  Electronics            7200.0

Products cheaper than 500:
 Empty DataFrame
Columns: [Product Name, Price, Category, Discounted Price]
Index: []


In [4]:
import numpy as np

array = np.random.randint(1, 101, size=(5, 5))
print("5x5 Random Array:\n", array)


5x5 Random Array:
 [[100  95  92   4  75]
 [ 86  36   7  42   6]
 [ 48  24  91  18  80]
 [ 37  14  72  55  50]
 [ 27  64  93  40  87]]


In [3]:
import pandas as pd

students = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Marks": [75, 82, 67, 90, 88]
}

df = pd.DataFrame(students)
print("Students DataFrame:\n", df)

print("\nStudents scoring more than 80:\n", df[df["Marks"] > 80])


Students DataFrame:
       Name  Marks
0    Alice     75
1      Bob     82
2  Charlie     67
3    David     90
4      Eva     88

Students scoring more than 80:
     Name  Marks
1    Bob     82
3  David     90
4    Eva     88


In [2]:
numbers = [1, 2, 3, 4, 5]
squares = [x**2 for x in numbers]
print("Squares:", squares)


Squares: [1, 4, 9, 16, 25]


In [ ]:
def is_palindrome(s):
    s = s.lower().replace(" ", "")  # ignore spaces and case
    return s == s[::-1]

# User input
user_input = input("Enter a string:")
if is_palindrome(user_input):
    print("It is a palindrome!")
else:
    print("Not a palindrome.")


It is a palindrome!
